# Nombre del pipeline
name: CI-Chepeat

# Disparador para la rama de desarrollo
trigger:
  branches:
    include:
      - development

# Jobs del pipeline
jobs:
- job: build
  displayName: 'Construir y validar código'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  # 1. Chequear código (puedes agregar análisis estático o linting)
  - task: Bash@3
    displayName: 'Run linting (opcional)'
    inputs:
      targetType: 'inline'
      script: |
        npm install
        npm run lint

  # 2. Construcción del proyecto
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Instalar Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Construir proyecto'

  # 3. Pruebas (si las tienes configuradas)
  - script: |
      npm run test
    displayName: 'Ejecutar pruebas'
